# There is the fix for a build script.

diff --git a/buildew b/buildew
--- a/buildew
+++ b/buildew
@@ -3,7 +3,15 @@
 COMMAND=$1
 
 if [ $COMMAND == "build" ]; then
-    docker build -f Dockerfile -t kws . --progress=plain
+    docker build -f Dockerfile -t usalko/kws:1.0.0 . --progress=plain
+fi
+
+if [ $COMMAND == "publish" ]; then
+    IMAGE=usalko/kws:1.0.0
+    docker push "$IMAGE" || {
+        echo "Line 274: Error in push to dockerhub image $IMAGE... Exit..."
+        exit 1
+    }
 fi
 
 if [ $COMMAND == "test" ]; then
@@ -13,8 +21,10 @@ if [ $COMMAND == "test" ]; then
         --header "Upgrade: websocket" \
         --header "Host: localhost:8801" \
         --header "Origin: http://localhost:8801" \
-        --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
+        --header "Sec-WebSocket-Key: MTIzNDU2Nzg5MDEyMzQ1Ng==" \
         --header "Sec-WebSocket-Version: 13" \
         http://localhost:8801/ws
 fi
+
+
 
